version: '2'

services:
  cashback-app:
    container_name: cashback-app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
    - postgres_db
    networks:
      - global-network

  postgres_db:
      container_name: postgres_db
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_USER: docker
        POSTGRES_PASSWORD: docker
        POSTGRES_DB: cashback
      ports:
      - "5431:5432"
      volumes_from:
      - data
      networks:
        - global-network

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

volumes:
    databasevolume: {}

networks:
    global-network:
        external: true