# Generated by Django 3.1 on 2020-08-08 05:38

import core.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[core.validators.validate_cpf], verbose_name='CPF')),
                ('email', models.EmailField(error_messages={'unique': 'Revendedor com esse email já existe.'}, max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('status', models.CharField(choices=[('in_validation', 'Em validação'), ('approve', 'Aprovado')], default='in_validation', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_code', models.CharField(max_length=100, unique=True, verbose_name='Código da Compra')),
                ('value', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Valor da Compra')),
                ('purchase_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dealer')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
