# Generated by Django 3.1 on 2020-08-10 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='cashback_percentage',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='cashback_value',
        ),
        migrations.CreateModel(
            name='CachbackPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Percentual do cashback')),
                ('cashback_value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor do Cashback')),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cashback', to='core.purchase')),
            ],
            options={
                'verbose_name': 'Cashback Compra',
            },
        ),
    ]
